language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "alex-1996"
    token:
      secure: d7762b2a5990e910ad3d768c3fa0cd0c15edb48c
script:
  - ant build
  - sonar-scanner